/* eslint-disable */
// MULTILINGUAL CONTENT PIPELINE
// Reads content/blog/<locale>/*.md (en, ko, cn), compiles to
// src/blog/generated-posts.js, keeps package.json reactSnap.include in sync,
// and regenerates public/sitemap.xml with hreflang clusters.

const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const MarkdownIt = require('markdown-it');

const md = new MarkdownIt({ html: true, linkify: true, typographer: true });

const ROOT = path.resolve(__dirname, '..');
const BLOG_DIR = path.join(ROOT, 'content', 'blog');
const OUT_FILE = path.join(ROOT, 'src', 'blog', 'generated-posts.js');
const PKG_FILE = path.join(ROOT, 'package.json');
const SITEMAP_FILE = path.join(ROOT, 'public', 'sitemap.xml');
const BASE = 'https://www.ppmcocopeat.com';

// Blog locales: folder name = URL path segment (en is the default at /blog).
const BLOG_LOCALES = ['en', 'ko', 'cn'];
// URL path segment -> hreflang code (cn path serves Chinese => zh).
const HREFLANG = { en: 'en', es: 'es', nl: 'nl', fr: 'fr', cn: 'zh', ko: 'ko' };

// Homepage languages + market pages (always prerendered).
const HOMEPAGE_LANGS = ['en', 'es', 'nl', 'fr', 'cn', 'ko'];
const MARKET_SLUGS = ['south-korea', 'netherlands', 'united-states', 'australia', 'new-zealand', 'spain'];

function renderBody(markdown) {
  let html = md.render(markdown || '');
  html = html.replace(/https:\/\/www\.ppmcocopeat\.com/g, '');
  html = html.replace(/href="\/#/g, 'href="/en#');
  return html;
}

function blogPath(locale, slug) {
  const prefix = locale === 'en' ? '' : `/${locale}`;
  return `${prefix}/blog${slug ? '/' + slug : ''}`;
}

function readLocale(locale) {
  const dir = path.join(BLOG_DIR, locale);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith('.md')).map((file) => {
    const { data, content } = matter(fs.readFileSync(path.join(dir, file), 'utf8'));
    const slug = data.slug || file.replace(/\.md$/, '');
    const faqs = Array.isArray(data.faqs)
      ? data.faqs.map((f) => ({ q: f.question || f.q || '', a: f.answer || f.a || '' }))
      : [];
    return {
      slug,
      locale,
      focusKeyword: data.focusKeyword || '',
      secondaryKeywords: data.secondaryKeywords || [],
      metaTitle: data.metaTitle || data.title || '',
      metaDescription: data.metaDescription || '',
      h1: data.title || '',
      excerpt: data.excerpt || '',
      category: data.category || 'Guide',
      readingTime: data.readingTime || '',
      datePublished: String(data.date || '2026-08-22'),
      dateModified: String(data.dateModified || data.date || '2026-08-22'),
      image: data.image || '/assets/coco-block.jpeg',
      faqs,
      bodyHtml: renderBody(content.trim()),
    };
  }).sort((a, b) => (a.datePublished < b.datePublished ? 1 : -1));
}

const postsByLang = {};
BLOG_LOCALES.forEach((l) => { postsByLang[l] = readLocale(l); });
// Fallback: any locale missing a slug falls back to the English post.
const enSlugs = postsByLang.en.map((p) => p.slug);
BLOG_LOCALES.filter((l) => l !== 'en').forEach((l) => {
  const have = new Set(postsByLang[l].map((p) => p.slug));
  enSlugs.forEach((slug) => {
    if (!have.has(slug)) {
      const en = postsByLang.en.find((p) => p.slug === slug);
      postsByLang[l].push({ ...en, locale: l });
    }
  });
});

// --- write generated-posts.js ---
function writeGenerated() {
  const banner = '// AUTO-GENERATED by scripts/build-content.js from content/blog/<locale>/*.md — DO NOT EDIT.\n';
  const body =
    `export const BLOG_LOCALES = ${JSON.stringify(BLOG_LOCALES)};\n` +
    `export const BLOG_HREFLANG = ${JSON.stringify(HREFLANG)};\n\n` +
    `export const postsByLang = ${JSON.stringify(postsByLang, null, 2)};\n\n` +
    `export const posts = postsByLang.en;\n` +
    `export const getPostsForLang = (lang) => postsByLang[lang] || postsByLang.en;\n` +
    `export const getPost = (slug, lang) => getPostsForLang(lang).find((p) => p.slug === slug);\n`;
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, banner + body, 'utf8');
  console.log(`[build-content] wrote posts for ${BLOG_LOCALES.join(', ')} -> generated-posts.js`);
}

// --- sync reactSnap.include ---
function syncReactSnap() {
  const routes = [];
  HOMEPAGE_LANGS.forEach((l) => routes.push(`/${l}`));
  routes.push('/coco-peat-supplier');
  MARKET_SLUGS.forEach((s) => routes.push(`/coco-peat-supplier/${s}`));
  BLOG_LOCALES.forEach((l) => {
    routes.push(blogPath(l));
    postsByLang[l].forEach((p) => routes.push(blogPath(l, p.slug)));
  });
  const pkg = JSON.parse(fs.readFileSync(PKG_FILE, 'utf8'));
  pkg.reactSnap = pkg.reactSnap || {};
  pkg.reactSnap.include = routes;
  fs.writeFileSync(PKG_FILE, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
  console.log(`[build-content] reactSnap.include synced (${routes.length} routes)`);
}

// --- generate sitemap.xml with hreflang ---
function writeSitemap() {
  const parts = ['<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'];
  // Homepage cluster
  const homeAlts = HOMEPAGE_LANGS.map((l) => `    <xhtml:link rel="alternate" hreflang="${HREFLANG[l]}" href="${BASE}/${l}"/>`).join('\n') +
    `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${BASE}/en"/>`;
  HOMEPAGE_LANGS.forEach((l) => {
    parts.push(`  <url>\n    <loc>${BASE}/${l}</loc>\n${homeAlts}\n    <priority>${l === 'en' ? '1.0' : '0.8'}</priority>\n  </url>`);
  });
  // Markets
  parts.push(`  <url><loc>${BASE}/coco-peat-supplier</loc><priority>0.8</priority></url>`);
  MARKET_SLUGS.forEach((s) => parts.push(`  <url><loc>${BASE}/coco-peat-supplier/${s}</loc><priority>0.8</priority></url>`));
  // Blog index per locale
  BLOG_LOCALES.forEach((l) => parts.push(`  <url><loc>${BASE}${blogPath(l)}</loc><priority>0.7</priority></url>`));
  // Blog posts with hreflang cluster across locales
  enSlugs.forEach((slug) => {
    const alts = BLOG_LOCALES.map((l) => `    <xhtml:link rel="alternate" hreflang="${HREFLANG[l]}" href="${BASE}${blogPath(l, slug)}"/>`).join('\n') +
      `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${BASE}${blogPath('en', slug)}"/>`;
    const lastmod = (postsByLang.en.find((p) => p.slug === slug) || {}).dateModified || '2026-08-22';
    BLOG_LOCALES.forEach((l) => {
      parts.push(`  <url>\n    <loc>${BASE}${blogPath(l, slug)}</loc>\n${alts}\n    <lastmod>${lastmod}</lastmod>\n    <priority>0.7</priority>\n  </url>`);
    });
  });
  parts.push('</urlset>\n');
  fs.writeFileSync(SITEMAP_FILE, parts.join('\n'), 'utf8');
  console.log(`[build-content] sitemap.xml written`);
}

writeGenerated();
syncReactSnap();
writeSitemap();
