/* eslint-disable */
// AUTO CONTENT PIPELINE
// Reads content/blog/*.md (edited by Sveltia CMS), generates
// src/blog/generated-posts.js, and keeps package.json's reactSnap.include
// in sync so every blog post is prerendered. Runs on prebuild/prestart.

const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const MarkdownIt = require('markdown-it');

const md = new MarkdownIt({ html: true, linkify: true, typographer: true });

// Convert markdown to HTML and rewrite absolute site links to SPA-relative paths.
function renderBody(markdown) {
  let html = md.render(markdown || '');
  html = html.replace(/https:\/\/www\.ppmcocopeat\.com/g, '');
  html = html.replace(/href="\/#/g, 'href="/en#'); // homepage anchors live on /en
  return html;
}

const ROOT = path.resolve(__dirname, '..');
const CONTENT_DIR = path.join(ROOT, 'content', 'blog');
const OUT_FILE = path.join(ROOT, 'src', 'blog', 'generated-posts.js');
const PKG_FILE = path.join(ROOT, 'package.json');

// Static routes that always get prerendered (languages + market pages).
const STATIC_ROUTES = [
  '/en', '/es', '/nl', '/fr', '/cn', '/ko',
  '/blog',
  '/coco-peat-supplier',
  '/coco-peat-supplier/south-korea',
  '/coco-peat-supplier/netherlands',
  '/coco-peat-supplier/united-states',
  '/coco-peat-supplier/australia',
  '/coco-peat-supplier/new-zealand',
  '/coco-peat-supplier/spain',
];

function readPosts() {
  if (!fs.existsSync(CONTENT_DIR)) {
    console.warn('[build-content] no content/blog dir yet — writing empty posts');
    return [];
  }
  const files = fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith('.md'));
  const posts = files.map((file) => {
    const raw = fs.readFileSync(path.join(CONTENT_DIR, file), 'utf8');
    const { data, content } = matter(raw);
    const slug = data.slug || file.replace(/\.md$/, '');
    const faqs = Array.isArray(data.faqs)
      ? data.faqs.map((f) => ({ q: f.question || f.q || '', a: f.answer || f.a || '' }))
      : [];
    return {
      slug,
      focusKeyword: data.focusKeyword || '',
      secondaryKeywords: data.secondaryKeywords || [],
      metaTitle: data.metaTitle || data.title || '',
      metaDescription: data.metaDescription || '',
      h1: data.title || '',
      excerpt: data.excerpt || '',
      category: data.category || 'Guide',
      readingTime: data.readingTime || '',
      datePublished: String(data.date || '2026-08-22'),
      dateModified: String(data.dateModified || data.date || '2026-08-22'),
      image: data.image || '/assets/coco-block.jpeg',
      faqs,
      body: content.trim(),
      bodyHtml: renderBody(content.trim()),
    };
  });
  // Newest first
  posts.sort((a, b) => (a.datePublished < b.datePublished ? 1 : -1));
  return posts;
}

function writeGenerated(posts) {
  const banner =
    '// AUTO-GENERATED by scripts/build-content.js from content/blog/*.md — DO NOT EDIT.\n';
  const body =
    'export const posts = ' + JSON.stringify(posts, null, 2) + ';\n\n' +
    'export const getPost = (slug) => posts.find((p) => p.slug === slug);\n';
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, banner + body, 'utf8');
  console.log(`[build-content] wrote ${posts.length} posts -> src/blog/generated-posts.js`);
}

function syncReactSnap(posts) {
  const pkg = JSON.parse(fs.readFileSync(PKG_FILE, 'utf8'));
  const blogRoutes = posts.map((p) => `/blog/${p.slug}`);
  const include = [...STATIC_ROUTES, ...blogRoutes];
  pkg.reactSnap = pkg.reactSnap || {};
  pkg.reactSnap.include = include;
  fs.writeFileSync(PKG_FILE, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
  console.log(`[build-content] reactSnap.include synced (${include.length} routes)`);
}

const posts = readPosts();
writeGenerated(posts);
syncReactSnap(posts);
